[package]
name = "rust-hello-world"
version = "0.1.0"
authors = ["lucian giurgiuculesei <giurgiuculesei@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
futures = "0.3"
async-std = "1.7.0"
